apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-automation-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minio-automation
  template:
    metadata:
      labels:
        app: minio-automation
    spec:
      containers:
      - name: automation
        image: ${KO_DOCKER_REPO}/minio-automation/service:${kontrakt.sourceReference}
